import streamlit as st
from dotenv import load_dotenv
import os
import json
import base64
import time
from utils import generate_pdf, load_chat_history, save_chat_history

# Customizing the page configuration
st.set_page_config(
    page_title="Automated Course Content Generator",
    page_icon=":robot:",
    layout="wide",
    initial_sidebar_state="collapsed",
)

load_dotenv()

st.title("Automated Course Content Generator 🤖 (Dummy Mode)")

USER_AVATAR = "👤"
BOT_AVATAR = "🤖"

# --- Dummy Data Constants ---
DUMMY_OUTLINE = """Course Title: Introduction to Artificial Intelligence
Course details: 4 Weeks, 2 Modules
Overview: This course provides a foundational understanding of AI concepts.
Outcomes: 
- Understand basic AI terminology.
- Identify real-world applications of AI.
Curriculum:
Module 1: AI Fundamentals
Lesson 1.1: What is AI?
Lesson 1.2: History of AI
Module 2: Machine Learning Basics
Lesson 2.1: Supervised Learning
Lesson 2.2: Unsupervised Learning
"""

DUMMY_DICTATOR_JSON = """{
    "Module 1: AI Fundamentals": ["Lesson 1.1: What is AI?", "Lesson 1.2: History of AI"],
    "Module 2: Machine Learning Basics": ["Lesson 2.1: Supervised Learning", "Lesson 2.2: Unsupervised Learning"]
}"""

DUMMY_CONTENT_TEMPLATE = """# {lesson_name}

## Introduction
This is dummy content generated for **{lesson_name}** in module **{module_name}**. In a real scenario, this would be a detailed explanation generated by the AI model.

## Key Concepts
1. **Concept A**: Description of concept A relevant to {lesson_name}.
2. **Concept B**: Description of concept B.

## Real-world Application
Here is how {lesson_name} applies to the real world.

## Conclusion
Summary of the lesson.
"""

DUMMY_QUIZ = """# Quiz Questions
1. What is the main topic of this module?
a) Cooking
b) AI
c) Sports
d) Music
Answer: b) AI

2. Which is a type of Machine Learning?
a) Supervised
b) Super-fast
c) Super-hero
d) Super-market
Answer: a) Supervised
"""

# --- Helper Functions ---
def safe_rerun():
    if hasattr(st, 'rerun'):
        st.rerun()
    else:
        st.experimental_rerun()

# --- Main Logic ---

# Initialize or load chat history
if "messages" not in st.session_state:
    st.session_state.messages = load_chat_history()

# Sidebar with a button to delete chat history
with st.sidebar:
    if st.button("Delete Chat History"):
        st.session_state.messages = []
        save_chat_history([])

# Layout
col1, col2 = st.columns([3.0, 7.0])

with col1:
    st.header("Course Details 📋")
    # Interactive widgets for course details
    course_name = st.text_input("Course Name", value="Intro to AI")
    target_audience_edu_level = st.selectbox(
        "Target Audience Edu Level",
        ["Primary", "High School", "Diploma", "Bachelors", "Masters"]
    )
    difficulty_level = st.radio(
        "Course Difficulty Level",
        ["Beginner", "Intermediate", "Advanced"]
    )
    num_modules = st.slider(
        "No. of Modules",
        min_value=1, max_value=15, value=2
    )
    course_duration = st.text_input("Course Duration", value="4 Weeks")
    course_credit = st.text_input("Course Credit", value="2")

    # Save widget states in session_state
    st.session_state.course_name = course_name
    st.session_state.target_audience_edu_level = target_audience_edu_level
    st.session_state.difficulty_level = difficulty_level
    st.session_state.num_modules = num_modules
    st.session_state.course_duration = course_duration
    st.session_state.course_credit = course_credit

    button1, button2 = st.columns([1, 0.8])
    with button1:
        generate_button = st.button("Generate Course Outline", help="Click me to generate course outline!😁")
    with button2:
        if "pdf" in st.session_state:
            new_course_button = st.button("Start a New Course", help="Click me to start a new course!💡")
            if new_course_button:
                # Reset state
                keys_to_reset = ["course_name", "target_audience_edu_level", "difficulty_level", 
                                 "num_modules", "course_duration", "course_credit", "pdf", 
                                 "course_outline", "buttons_visible", "complete_course", "modifications"]
                for key in keys_to_reset:
                    if key in st.session_state:
                        del st.session_state[key]
                safe_rerun()

with col2:
    st.header("Generated Course Content 📝")
    
    # 1. Generate Outline
    if generate_button:
        # Include user selections in the message history
        user_selections = f"Course Name: {course_name}\nTarget Audience Edu Level: {target_audience_edu_level}\nDifficulty Level: {difficulty_level}\nNo. of Modules: {num_modules}\nCourse Duration: {course_duration}\nCourse Credit: {course_credit}"
        st.session_state.messages.append({"role": "user", "content": user_selections})
        save_chat_history(st.session_state.messages)

        with st.spinner("Generating course outline (Dummy Mode)..."):
            time.sleep(1.0) # Simulate delay
            st.session_state['course_outline'] = DUMMY_OUTLINE
            st.session_state['buttons_visible'] = True
            st.success("Course outline generated successfully!")

    # 2. Display Outline & Action Buttons
    if 'course_outline' in st.session_state:
        with st.expander("Course Outline", expanded=True):
            st.write(st.session_state['course_outline'])

        if 'buttons_visible' in st.session_state and st.session_state['buttons_visible']:
            b1, b2 = st.columns([1, 2])
            with b1:
                if st.button("Looks cool. Generate complete course!", key="btn_complete"):
                    st.session_state['complete_course'] = True
                    st.session_state['modifications'] = False
            with b2:
                if st.button("Wait, I need modifications", key="btn_modify"):
                    st.session_state['modifications'] = True
                    st.session_state['complete_course'] = False

    # 3. Handle Modifications
    if st.session_state.get('modifications') is True:
        mod_text = st.text_input("Please enter the modifications you'd like to make:")
        if mod_text:
            st.write("Applying modifications (Dummy Mode)...")
            st.session_state['course_outline'] = DUMMY_OUTLINE + f"\n\n(Modified with: {mod_text})"
            st.success("Modifications applied! You can now click 'Generate complete course' above.")
            # We revert modifications state so the user can proceed
            st.session_state['modifications'] = False 

    # 4. Generate Complete Course
    if st.session_state.get('complete_course') is True:
        with st.spinner("Generating complete course (Dummy Mode)..."):
            time.sleep(1)
            module_lessons = json.loads(DUMMY_DICTATOR_JSON)
            
            full_content_accumulator = ""

            for module_name, lessons in module_lessons.items():
                # Module Content
                module_text = ""
                for lesson_name in lessons:
                     with st.spinner(f"Generating content for {module_name}, {lesson_name}"):
                        time.sleep(0.3)
                        content = DUMMY_CONTENT_TEMPLATE.format(lesson_name=lesson_name, module_name=module_name)
                        module_text += content + "\n\n"
                        st.write(f"**{lesson_name}** generated.")
                        with st.expander(f"View {lesson_name}"):
                            st.write(content)

                # Quiz
                with st.spinner(f"Generating quiz for {module_name}"):
                    time.sleep(0.3)
                    quiz = DUMMY_QUIZ
                    st.write(f"**Quiz for {module_name}** generated.")
                    with st.expander("View Quiz"):
                        st.write(quiz)
                    module_text += "\n\n" + quiz
                
                full_content_accumulator += module_text + "\n\n"
                
                # In dummy mode, we just break after one module to keep it simple, or loop all
                # Let's loop all for better feel
            
            # PDF Generation
            if "pdf" not in st.session_state:
                st.session_state.pdf = True # Mark as done
                # We generate PDF from the accumulated content
                pdf_obj = generate_pdf(full_content_accumulator, "course.pdf")
                b64 = base64.b64encode(pdf_obj.output(dest="S").encode('latin1')).decode()
                
                st.success("All content generated! Your PDF is ready.")
                st.download_button(
                    label="Download PDF", 
                    data=b64, 
                    file_name="course.pdf", 
                    mime="application/pdf"
                )
        
        # Prevent re-running generation loop endlessly by checking if we just finished
        # In Streamlit, buttons reset on rerun, but here we used session_state flag.
        # Ideally we stop showing the 'Generating...' spinner once done.
        # But for this simple dummy flow, the download button appearing is the end state.