import streamlit as st
from dotenv import load_dotenv
import os
import json
import base64
import time
from utils import generate_pdf, load_chat_history, save_chat_history
# Prompts are not strictly needed for dummy mode but keeping imports to avoid breaking file structure expectations
from prompts.tabler_prompt import TABLER_PROMPT
from prompts.dictator_prompt import DICTATOR_PROMPT
from prompts.quizzy_prompt import QUIZZY_PROMPT

# Customizing the page configuration
st.set_page_config(
    page_title="Automated Course Content Generator",
    page_icon=":robot:",
    layout="wide",
    initial_sidebar_state="collapsed",
)

load_dotenv()

st.title("Automated Course Content Generator 🤖 (Dummy Mode)")

USER_AVATAR = "👤"
BOT_AVATAR = "🤖"

# Dummy Data Constants
DUMMY_OUTLINE = """Course Title: Introduction to Artificial Intelligence
Course details: 4 Weeks, 2 Modules
Overview: This course provides a foundational understanding of AI concepts.
Outcomes: 
- Understand basic AI terminology.
- Identify real-world applications of AI.
Curriculum:
Module 1: AI Fundamentals
Lesson 1.1: What is AI?
Lesson 1.2: History of AI
Module 2: Machine Learning Basics
Lesson 2.1: Supervised Learning
Lesson 2.2: Unsupervised Learning
"""

DUMMY_DICTATOR_JSON = """{
    "Module 1: AI Fundamentals": ["Lesson 1.1: What is AI?", "Lesson 1.2: History of AI"],
    "Module 2: Machine Learning Basics": ["Lesson 2.1: Supervised Learning", "Lesson 2.2: Unsupervised Learning"]
}"""

DUMMY_CONTENT_TEMPLATE = """# {lesson_name}

## Introduction
This is dummy content generated for **{lesson_name}** in module **{module_name}**. In a real scenario, this would be a detailed explanation generated by the AI model.

## Key Concepts
1. **Concept A**: Description of concept A relevant to {lesson_name}.
2. **Concept B**: Description of concept B.

## Real-world Application
Here is how {lesson_name} applies to the real world.

## Conclusion
Summary of the lesson.
"""

DUMMY_QUIZ = """# Quiz Questions
1. What is the main topic of this module?
a) Cooking
b) AI
c) Sports
d) Music
Answer: b) AI

2. Which is a type of Machine Learning?
a) Supervised
b) Super-fast
c) Super-hero
d) Super-market
Answer: a) Supervised
"""

# Initialize or load chat history
if "messages" not in st.session_state:
    st.session_state.messages = load_chat_history()

# Sidebar with a button to delete chat history
with st.sidebar:
    if st.button("Delete Chat History"):
        st.session_state.messages = []
        save_chat_history([])

# Example of using columns for advanced layouts
col1, col2 = st.columns([3.0, 0.1, 7.0])

with col1:
    st.header("Course Details 📋")
    # Interactive widgets for course details
    course_name = st.text_input("Course Name", value="Intro to AI")
    target_audience_edu_level = st.selectbox(
        "Target Audience Edu Level",
        ["Primary", "High School", "Diploma", "Bachelors", "Masters"]
    )
    difficulty_level = st.radio(
        "Course Difficulty Level",
        ["Beginner", "Intermediate", "Advanced"]
    )
    num_modules = st.slider(
        "No. of Modules",
        min_value=1, max_value=15, value=2
    )
    course_duration = st.text_input("Course Duration", value="4 Weeks")
    course_credit = st.text_input("Course Credit", value="2")

    # Save widget states in session_state
    st.session_state.course_name = course_name
    st.session_state.target_audience_edu_level = target_audience_edu_level
    st.session_state.difficulty_level = difficulty_level
    st.session_state.num_modules = num_modules
    st.session_state.course_duration = course_duration
    st.session_state.course_credit = course_credit

    button1, button2 = st.columns([1, 0.8])
    with button1:
        generate_button = st.button("Generate Course Outline", help="Click me to generate course outline!😁")
    with button2:
        if "pdf" in st.session_state:
            new_course_button = st.button("Start a New Course", help="Click me to start a new course!💡")
            if new_course_button:
                st.session_state.course_name = ""
                st.session_state.target_audience_edu_level = ""
                st.session_state.difficulty_level = ""
                st.session_state.num_modules = 1
                st.session_state.course_duration = ""
                st.session_state.course_credit = ""
                st.session_state.pdf = False
                st.experimental_rerun()

with col2:
    st.header("Generated Course Content 📝")
    # Display the generated content here
    if generate_button and "pdf" not in st.session_state:
        # Include user selections in the message history
        user_selections = f"Course Name: {course_name}\nTarget Audience Edu Level: {target_audience_edu_level}\nDifficulty Level: {difficulty_level}\nNo. of Modules: {num_modules}\nCourse Duration: {course_duration}\nCourse Credit: {course_credit}"
        st.session_state.messages.append({"role": "user", "content": user_selections})

        # MOCK: Prompt generation
        generated_prompt = "Mock generated prompt based on user input."
        
        with st.spinner("Generating course outline (Dummy Mode)..."):
            time.sleep(1.5) # Simulate API latency
            Course_outline = DUMMY_OUTLINE
            st.success("Course outline generated successfully!")

            st.session_state['course_outline'] = Course_outline
            st.session_state['buttons_visible'] = True

    if 'course_outline' in st.session_state and "pdf" not in st.session_state:
        with st.expander("Course Outline"):
            st.write(st.session_state['course_outline'])

        if 'buttons_visible' in st.session_state and st.session_state['buttons_visible']:
            button1, button2 = st.columns([1, 2])
            with button1:
                complete_course_button = st.button("Looks cool. Generate complete course!", help="Click me to generate complete course!😍")
            with button2:
                modifications_button = st.button("Wai wait..!, I need to make some modifications", help="Click me to modify the course outline!🧐")

            # Handle button actions
            if complete_course_button:
                st.session_state['complete_course'] = True
                st.session_state['modifications'] = False
            elif modifications_button:
                st.session_state['modifications'] = True
                st.session_state['complete_course'] = False

            if 'complete_course' in st.session_state and st.session_state['complete_course']:
                with st.spinner("Generating complete course (Dummy Mode)..."):
                    # MOCK: Convert outline to JSON
                    time.sleep(1)
                    Dict = DUMMY_DICTATOR_JSON
                    
                    module_lessons = json.loads(Dict)

                    for module_name in module_lessons:
                        module_content = ""

                        for lesson_name in module_lessons[module_name]:
                            
                            with st.spinner(f"Generating content for {module_name}, {lesson_name}"):
                                # MOCK: Generate lesson content
                                time.sleep(0.5)
                                complete_course = DUMMY_CONTENT_TEMPLATE.format(lesson_name=lesson_name, module_name=module_name)
                                st.success(f"Generated content for {module_name}, {lesson_name}")

                                with st.expander("Click to view!"):
                                    st.write(complete_course)
                                
                                module_content +=  complete_course + "\n"*2
                        
                        # MOCK: Generate Quiz
                        with st.spinner(f"Generating quiz questions for {module_name}"):
                            time.sleep(0.5)
                            quiz_questions = DUMMY_QUIZ

                            st.success(f"Quiz time!! Generated quiz questions for {module_name}")
                            with st.expander("Click to view!"):
                                st.write(quiz_questions)

                            if "pdf" not in st.session_state:
                                complete_course_content = module_content + "\n\n" + quiz_questions
                                st.session_state.pdf = generate_pdf(complete_course_content, "course.pdf")
                                b64 = base64.b64encode(st.session_state.pdf.output(dest="S").encode('latin1')).decode()
                                st.success("Your PDF file is ready!")

                            button_label = "Download PDF"
                            st.download_button(label=button_label, data=b64, file_name="course.pdf", mime="application/pdf", key="download_pdf_button")
                                    
                        break # Break after first module for dummy demo speed
                
            elif 'modifications' in st.session_state:
                modifications = st.text_input("Please enter the modifications you'd like to make:")
                if modifications:
                    st.session_state.modifications = modifications
                    
                    # MOCK: Modifying course outline
                    st.write("Applying modifications (Dummy Mode)...")
                    st.session_state['course_outline'] = DUMMY_OUTLINE + f"\n(Modified with: {modifications})"
                    
                    # Trigger generation flow again or just show updated outline
                    st.success("Modifications applied! (Click 'Generate complete course' to proceed with original dummy flow)")

    else:
        st.write("Your generated content will appear here.")

# Save chat history after each interaction
save_chat_history(st.session_state.messages)